"""M0 baseline schema — materializes all tables from model metadata.

This is the initial migration for the skeleton. It creates the full schema
defined by the ORM models in one shot. From M1 onward, schema changes should
be captured as ordinary autogenerated incremental migrations on top of this.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-09-21
"""
from __future__ import annotations

from alembic import op

from app.db import Base
import app.models  # noqa: F401  (registers all tables on Base.metadata)

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
